[env:heltec_ct62]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Serial Monitor Speed
monitor_speed = 115200

; Library Dependencies
lib_deps =
    jgromes/RadioLib @ ^6.6.0
    olikraus/U8g2 @ ^2.35.19

; Build Flags for ESP32-C3
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Optimization: Helps with the packed struct memory alignment
build_type = release